modLoader="javafml"
loaderVersion="[43,)"
license="${mod_license}"

[[mods]]
modId="skinmod"
version="${mod_version}"
displayName="Skin Mod"
description='''${mod_description}'''

[[dependencies.skinmod]]
 modId="forge"
 mandatory=true
 versionRange="[43,)"
 ordering="NONE"
 side="BOTH"

[[dependencies.skinmod]]
 modId="minecraft"
 mandatory=true
 versionRange="[1.19.2,1.20)"
 ordering="NONE"
 side="BOTH"

[[mixins]]
config = "skinmod.mixins.json"
